#VIA_ENABLE=yes
#VIAL_ENABLE=yes
#
#VIALRGB_ENABLE=yes
#VIAL_ENCODERS_ENABLE = yes

#define VIAL_UNLOCK_ROWS { 1,3 }
#define VIAL_UNLOCK_COLS { 10,4 }

#CONSOLE_ENABLE = yes
OPENRGB_ENABLE = yes
DEBOUNCE_TYPE = sym_eager_pk
